<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.1.7</Version>
    <Author>Splash</Author>
    <Name>Splash's Crucible Solver</Name>
    <Punchline>Accessibility and information tools for the BST Crucible.</Punchline>
    <Description>Provides additional UI and calculated information for BST Crucible content.</Description>
    <RepoUrl>https://github.com/dancematgame/SplashCrucible</RepoUrl>
    <Tags>bst;crucible;accessibility</Tags>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
