<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.1.0</Version>
    <Author>Splash</Author>
    <Name>Splash Crucible</Name>
    <Punchline>Accessibility and information tools for the Beastmaster Crucible.</Punchline>
    <Description>Provides additional UI and calculated information for FFXIV Beastmaster Crucible content.</Description>
    <RepoUrl>https://github.com/dancematgame/SplashCrucible</RepoUrl>
    <Tags>beastmaster;crucible;accessibility</Tags>
  </PropertyGroup>
</Project>
